/*
 * Copyright (C) 2015 Max Dowkes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 */
package cycgui;

import cyccore.Booking;
import cyccore.CYCDate;
import cyccore.Customer;
import cyccore.InitialisedObjects;
import cyccore.*;
import cycfacade.CYCFacade;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Max Dowkes
 */
public class SetUpGUI1A extends javax.swing.JFrame
{

    CYCFacade cycf = new CYCFacade();
    Map<Integer, Booking> bookingMap;// = new HashMap<Integer, Booking>();
    Map<Integer, Customer> customerMap;
    Map<Integer, Room> roomMap;
    Map<Integer, EndTime> endTimeMap;
    Map<Integer, StartTime> startTimeMap;
    Scheduler scheduler = new Scheduler();

    /**
     * Creates new form SetUpGUI
     */
    public SetUpGUI1A()
    {
        this.listModel = new DefaultListModel();
        initComponents();

        this.setUpBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addCustomerPanel = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        addCustomerNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        addCustomerJButton = new javax.swing.JButton();
        makeBookingPanel = new javax.swing.JPanel();
        makeBookingDateJTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        makeBookingRoomJComboBox = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        makeBookingStartTimeJComboBox = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        makeBookingEndTimeJComboBox = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        makeBookingJButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        makeBookingCustomerJComboBox = new javax.swing.JComboBox();
        attendeesJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        repeatBookingJCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        repeatBookingsJTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        changeBookingPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel31 = new javax.swing.JLabel();
        changeDateField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        changeRoomCombobox = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        changeStartTimeCombobox = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        changeEndTimeCombobox = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        changeCustomerField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancelBookingsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cancelBookingJList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelBookingJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewCustomerField = new javax.swing.JTextField();
        viewRoomField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        viewStartTimeField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        viewDateField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        viewEndTimeField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        viewBookingsPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        viewCustomerField1 = new javax.swing.JTextField();
        viewRoomField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        viewStartTimeField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        viewDateField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        viewEndTimeField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Add Customer Details Panel");

        addCustomerNameField.setText("Enter Name");

        jLabel2.setText("Customer");

        jLabel39.setText("Add Customer");

        addCustomerJButton.setText("Add Customer");
        addCustomerJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addCustomerJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addCustomerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCustomerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomerJButton)
                .addGap(0, 406, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer Details", addCustomerPanel);

        makeBookingDateJTextField.setText(CYCDate.getTodaysDate());

        jLabel24.setText("Enter Date dd/mm/yy");

        jLabel25.setText("Select Room");

        jLabel26.setText("Select Start Time");

        jLabel27.setText("Select End Time");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Click To Make Booking");

        makeBookingJButton.setText("Make Booking");
        makeBookingJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                makeBookingJButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Make Booking Panel");

        makeBookingCustomerJComboBox.setMinimumSize(new java.awt.Dimension(79, 24));
        makeBookingCustomerJComboBox.setPreferredSize(new java.awt.Dimension(79, 24));

        attendeesJTextField.setText("jTextField1");

        jLabel3.setText("Attendees");

        repeatBookingJCheckBox.setText("Yes");

        jLabel5.setText("Booking Repeats");

        jLabel9.setText("Enter Number of Weeks");

        repeatBookingsJTextField.setText("1");

        jLabel38.setText("Customer");

        javax.swing.GroupLayout makeBookingPanelLayout = new javax.swing.GroupLayout(makeBookingPanel);
        makeBookingPanel.setLayout(makeBookingPanelLayout);
        makeBookingPanelLayout.setHorizontalGroup(
            makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(makeBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeBookingPanelLayout.createSequentialGroup()
                        .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(makeBookingDateJTextField)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeBookingRoomJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeBookingStartTimeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeBookingEndTimeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(makeBookingPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(attendeesJTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(makeBookingPanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(makeBookingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(makeBookingPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(makeBookingCustomerJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(repeatBookingJCheckBox)
                    .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(repeatBookingsJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        makeBookingPanelLayout.setVerticalGroup(
            makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeBookingPanelLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeBookingDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeBookingCustomerJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeBookingRoomJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendeesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(makeBookingStartTimeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeBookingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(makeBookingEndTimeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(makeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(makeBookingPanelLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(33, 33, 33))
                        .addComponent(makeBookingJButton)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatBookingJCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatBookingsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Make Booking", makeBookingPanel);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Change Bookings Panel");

        jLabel30.setText("Select Booking From List");

        jList3.setModel(listModel);
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jLabel31.setText("Selected Booking");

        changeDateField.setText(CYCDate.getTodaysDate());

        jLabel32.setText("Change Date dd/mm/yy");

        jLabel33.setText("Change Room");

        changeRoomCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Room 1", "Room 2", "Room 3", "Room 4", "Room 5", "Pitch 1", "Pitch 2" }));

        jLabel34.setText("Change Start Time");

        changeStartTimeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm" }));

        jLabel35.setText("Change End Time");

        changeEndTimeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm" }));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Click To Change Booking");

        jButton4.setText("Change Booking");

        changeCustomerField.setText("jTextField1");

        jLabel1.setText("Customer");

        javax.swing.GroupLayout changeBookingPanelLayout = new javax.swing.GroupLayout(changeBookingPanel);
        changeBookingPanel.setLayout(changeBookingPanelLayout);
        changeBookingPanelLayout.setHorizontalGroup(
            changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(changeBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addGroup(changeBookingPanelLayout.createSequentialGroup()
                        .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeDateField)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeRoomCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeStartTimeCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeEndTimeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changeBookingPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel36))
                            .addGroup(changeBookingPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton4))
                            .addGroup(changeBookingPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(changeCustomerField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        changeBookingPanelLayout.setVerticalGroup(
            changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeBookingPanelLayout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeCustomerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeRoomCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(changeBookingPanelLayout.createSequentialGroup()
                        .addGroup(changeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changeStartTimeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35))
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(changeEndTimeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Change Booking", changeBookingPanel);

        cancelBookingJList.setModel(listModel);
        cancelBookingJList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                cancelBookingJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(cancelBookingJList);

        jLabel6.setText("Select Booking From List");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cancel Selected Booking");

        cancelBookingJButton.setText("Cancel Booking");
        cancelBookingJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelBookingJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Selected Booking");

        jLabel10.setText("Customer");
        jLabel10.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 20));

        viewCustomerField.setEditable(false);
        viewCustomerField.setMaximumSize(new java.awt.Dimension(150, 20));
        viewCustomerField.setMinimumSize(new java.awt.Dimension(80, 20));
        viewCustomerField.setPreferredSize(new java.awt.Dimension(80, 20));

        viewRoomField.setEditable(false);
        viewRoomField.setMaximumSize(new java.awt.Dimension(150, 20));
        viewRoomField.setMinimumSize(new java.awt.Dimension(80, 20));
        viewRoomField.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel11.setText("Room");
        jLabel11.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(80, 20));

        viewStartTimeField.setEditable(false);
        viewStartTimeField.setMaximumSize(new java.awt.Dimension(150, 20));
        viewStartTimeField.setMinimumSize(new java.awt.Dimension(80, 20));
        viewStartTimeField.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel12.setText("Start Time");
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 20));

        viewDateField.setEditable(false);
        viewDateField.setMaximumSize(new java.awt.Dimension(150, 20));
        viewDateField.setMinimumSize(new java.awt.Dimension(80, 20));
        viewDateField.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel13.setText("Date");
        jLabel13.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 20));

        viewEndTimeField.setEditable(false);
        viewEndTimeField.setMaximumSize(new java.awt.Dimension(150, 20));
        viewEndTimeField.setMinimumSize(new java.awt.Dimension(80, 20));
        viewEndTimeField.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel14.setText("End Time");
        jLabel14.setMaximumSize(new java.awt.Dimension(80, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cancel Booking Panel");

        javax.swing.GroupLayout cancelBookingsPanelLayout = new javax.swing.GroupLayout(cancelBookingsPanel);
        cancelBookingsPanel.setLayout(cancelBookingsPanelLayout);
        cancelBookingsPanelLayout.setHorizontalGroup(
            cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(148, 148, 148)))
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(cancelBookingJButton))
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewCustomerField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewStartTimeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewRoomField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(viewDateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(viewEndTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cancelBookingsPanelLayout.setVerticalGroup(
            cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBookingJButton))
                    .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addComponent(viewCustomerField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewRoomField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cancelBookingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cancelBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewStartTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewEndTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Booking", cancelBookingsPanel);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("View Bookings Panel");

        jLabel8.setText("Select Booking From List");

        jList2.setModel(listModel);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel15.setText("Selected Booking");

        jLabel16.setText("Customer");
        jLabel16.setMaximumSize(new java.awt.Dimension(150, 20));
        jLabel16.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel16.setPreferredSize(new java.awt.Dimension(80, 20));

        viewCustomerField1.setEditable(false);
        viewCustomerField1.setMinimumSize(new java.awt.Dimension(80, 20));
        viewCustomerField1.setPreferredSize(new java.awt.Dimension(80, 20));

        viewRoomField1.setEditable(false);
        viewRoomField1.setMinimumSize(new java.awt.Dimension(80, 20));
        viewRoomField1.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel17.setText("Room");
        jLabel17.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(80, 20));

        viewStartTimeField1.setEditable(false);
        viewStartTimeField1.setMinimumSize(new java.awt.Dimension(80, 20));
        viewStartTimeField1.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel18.setText("Start Time");
        jLabel18.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel18.setPreferredSize(new java.awt.Dimension(80, 20));

        viewDateField1.setEditable(false);
        viewDateField1.setMinimumSize(new java.awt.Dimension(80, 20));
        viewDateField1.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel19.setText("Date");
        jLabel19.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel19.setPreferredSize(new java.awt.Dimension(80, 20));

        viewEndTimeField1.setEditable(false);
        viewEndTimeField1.setMinimumSize(new java.awt.Dimension(80, 20));
        viewEndTimeField1.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel20.setText("End Time");
        jLabel20.setMinimumSize(new java.awt.Dimension(80, 20));
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout viewBookingsPanelLayout = new javax.swing.GroupLayout(viewBookingsPanel);
        viewBookingsPanel.setLayout(viewBookingsPanelLayout);
        viewBookingsPanelLayout.setHorizontalGroup(
            viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(viewBookingsPanelLayout.createSequentialGroup()
                        .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewStartTimeField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRoomField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEndTimeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewCustomerField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(203, Short.MAX_VALUE))
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewBookingsPanelLayout.setVerticalGroup(
            viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBookingsPanelLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCustomerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewRoomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewStartTimeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewEndTimeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Bookings", viewBookingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("New Booking");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jList2ValueChanged
    {//GEN-HEADEREND:event_jList2ValueChanged
        // TODO add your handling code here:
        this.viewBookingTextFields(jList2);
        System.out.println(jList2.getSelectedIndex());
    }//GEN-LAST:event_jList2ValueChanged

    private void cancelBookingJListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_cancelBookingJListValueChanged
    {//GEN-HEADEREND:event_cancelBookingJListValueChanged
        // TODO add your handling code here:
        this.viewBookingTextFields(cancelBookingJList);
        System.out.println(cancelBookingJList.getSelectedIndex());
    }//GEN-LAST:event_cancelBookingJListValueChanged

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
        // TODO add your handling code here:
        this.viewBookingTextFields(jList3);
        System.out.println(jList3.getSelectedIndex());
    }//GEN-LAST:event_jList3ValueChanged

    private void cancelBookingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingJButtonActionPerformed
        // TODO add your handling code here:
        Booking selectedBooking = (Booking) this.listModel.get(
                cancelBookingJList.getSelectedIndex());
        cycf.cancelBooking(selectedBooking.getID());
        System.out.println("Selected booking is: " + selectedBooking);
        listModel.removeElementAt(cancelBookingJList.getSelectedIndex());

    }//GEN-LAST:event_cancelBookingJButtonActionPerformed

    private void makeBookingJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_makeBookingJButtonActionPerformed
    {//GEN-HEADEREND:event_makeBookingJButtonActionPerformed

        if (repeatBookingJCheckBox.isSelected() == true)
        {
            String dateString = makeBookingDateJTextField.getText();
            Date date = null;
            try
            {
                date = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);
            }
            catch (ParseException ex)
            {
                Logger.getLogger(SetUpGUI1A.class.getName()).log(Level.SEVERE,
                        null, ex);
            }
            Map<Integer, CYCDate> dateMap = new TreeMap<Integer, CYCDate>();
            dateMap = scheduler.repeatBookings(dateString, Integer.parseInt(
                    repeatBookingsJTextField.getText()));

            System.out.println("Datemap is: " + dateMap);

            int iteration = 0;

            for (CYCDate eachDate : dateMap.values())
            {
                Booking newBooking;

                Customer customer = (Customer) makeBookingCustomerJComboBox.getSelectedItem();
                System.out.println("Customer is: " + customer);
                StartTime startTime = (StartTime) makeBookingStartTimeJComboBox.getSelectedItem();
                EndTime endTime = (EndTime) makeBookingEndTimeJComboBox.getSelectedItem();
                Room room = (Room) makeBookingRoomJComboBox.getSelectedItem();
                int attendees = Integer.parseInt(attendeesJTextField.getText());

                iteration++;
                CYCDate aCYCDate = dateMap.get(eachDate.getDateID());

                newBooking = new Booking(customer, startTime, endTime, room,
                        aCYCDate, attendees);
                System.out.println(
                        "NEW BOOKING " + iteration + " IS: " + newBooking);
                cycf.newInsertData(newBooking);
            }
        }

        else
        {
            Booking newBooking;

            Customer customer = (Customer) makeBookingCustomerJComboBox.getSelectedItem();
            System.out.println("Customer is: " + customer);
            StartTime startTime = (StartTime) makeBookingStartTimeJComboBox.getSelectedItem();
            EndTime endTime = (EndTime) makeBookingEndTimeJComboBox.getSelectedItem();
            Room room = (Room) makeBookingRoomJComboBox.getSelectedItem();
            int attendees = Integer.parseInt(attendeesJTextField.getText());
            String dateString = makeBookingDateJTextField.getText();

            CYCDate aCYCDate = null;
            try
            {
                Date date = new SimpleDateFormat("dd/MM/yy").parse(dateString);
                aCYCDate = new CYCDate(date.getTime());
            }

            catch (ParseException ex)
            {
                ex.printStackTrace();
            }
            newBooking = new Booking(customer, startTime, endTime, room,
                    aCYCDate, attendees);

            cycf.newInsertData(newBooking);
        }
       
        updateListModel();
    }//GEN-LAST:event_makeBookingJButtonActionPerformed

    private void addCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addCustomerJButtonActionPerformed
    {//GEN-HEADEREND:event_addCustomerJButtonActionPerformed
        // TODO add your handling code here:
        String customerName = addCustomerNameField.getText();
        cycf.addCustomer(customerName);
    }//GEN-LAST:event_addCustomerJButtonActionPerformed

    public void updateListModel()
    {
        listModel.removeAllElements();
        bookingMap = cycf.getBookingMap();

        for (Booking eachBooking : bookingMap.values())
        {
            listModel.addElement(eachBooking);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SetUpGUI1A.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SetUpGUI1A.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SetUpGUI1A.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SetUpGUI1A.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    /* Create and display the form */

    public static void run()
    {

        InitialisedObjects io = new InitialisedObjects();

        new SetUpGUI1A().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerJButton;
    private javax.swing.JTextField addCustomerNameField;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JTextField attendeesJTextField;
    private javax.swing.JButton cancelBookingJButton;
    private javax.swing.JList cancelBookingJList;
    private javax.swing.JPanel cancelBookingsPanel;
    private javax.swing.JPanel changeBookingPanel;
    private javax.swing.JTextField changeCustomerField;
    private javax.swing.JTextField changeDateField;
    private javax.swing.JComboBox changeEndTimeCombobox;
    private javax.swing.JComboBox changeRoomCombobox;
    private javax.swing.JComboBox changeStartTimeCombobox;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox makeBookingCustomerJComboBox;
    private javax.swing.JTextField makeBookingDateJTextField;
    private javax.swing.JComboBox makeBookingEndTimeJComboBox;
    private javax.swing.JButton makeBookingJButton;
    private javax.swing.JPanel makeBookingPanel;
    private javax.swing.JComboBox makeBookingRoomJComboBox;
    private javax.swing.JComboBox makeBookingStartTimeJComboBox;
    private javax.swing.JCheckBox repeatBookingJCheckBox;
    private javax.swing.JTextField repeatBookingsJTextField;
    private javax.swing.JPanel viewBookingsPanel;
    private javax.swing.JTextField viewCustomerField;
    private javax.swing.JTextField viewCustomerField1;
    private javax.swing.JTextField viewDateField;
    private javax.swing.JTextField viewDateField1;
    private javax.swing.JTextField viewEndTimeField;
    private javax.swing.JTextField viewEndTimeField1;
    private javax.swing.JTextField viewRoomField;
    private javax.swing.JTextField viewRoomField1;
    private javax.swing.JTextField viewStartTimeField;
    private javax.swing.JTextField viewStartTimeField1;
    // End of variables declaration//GEN-END:variables
      private DefaultListModel listModel;

    public void setUpBookings()
    {
        bookingMap = cycf.getBookingMap();
        customerMap = cycf.getCustomerMap();
        roomMap = cycf.getRoomMap();
        startTimeMap = cycf.getStartTimeMap();
        endTimeMap = cycf.getEndTimeMap();

        for (Booking eachBooking : bookingMap.values())
        {
            listModel.addElement(eachBooking);

        }
        for (Customer eachCustomer : customerMap.values())
        {
            makeBookingCustomerJComboBox.addItem(eachCustomer);
        }

        for (Room eachRoom : roomMap.values())
        {
            makeBookingRoomJComboBox.addItem(eachRoom);
        }

        for (StartTime eachStartTime : startTimeMap.values())
        {
            makeBookingStartTimeJComboBox.addItem(eachStartTime);
        }
        for (EndTime eachEndTime : endTimeMap.values())
        {
            makeBookingEndTimeJComboBox.addItem(eachEndTime);
        }

        /*
         * This code is used to set up initial text fields,
         * there must be a better way than this.
         *
         * NEEDS REFACTORING
         */
        Booking firstBooking;// = new Booking();
        if (!bookingMap.isEmpty())
        {
            firstBooking = (Booking) listModel.get(0);

            String aRoom = firstBooking.getRoom().toString();
            String aCustomer = firstBooking.getCustomer().toString();
            String aDate = firstBooking.getDate().toString();
            String aStartTime = firstBooking.getStartTime().toString();
            String aEndTime = firstBooking.getEndTime().toString();

            viewCustomerField.setText(aCustomer);
            viewRoomField.setText(aRoom);
            viewDateField.setText(aDate);
            viewStartTimeField.setText(aStartTime);
            viewEndTimeField.setText(aEndTime);
            viewCustomerField1.setText(aCustomer);
            viewRoomField1.setText(aRoom);
            viewDateField1.setText(aDate);
            viewStartTimeField1.setText(aStartTime);
            viewEndTimeField1.setText(aEndTime);
        }
    }

    public void viewBookingTextFields(JList aJList)
    {
        Booking selectedBooking = (Booking) aJList.getSelectedValue();

        if (selectedBooking != null)
        {
            String aRoom = selectedBooking.getRoom().toString();
            String aCustomer = selectedBooking.getCustomer().toString();
            String aDate = selectedBooking.getDate().toString();
            String aStartTime = selectedBooking.getStartTime().toString();
            String aEndTime = selectedBooking.getEndTime().toString();
            if (aJList == jList2)
            {
                viewCustomerField1.setText(aCustomer);
                viewRoomField1.setText(aRoom);
                viewDateField1.setText(aDate);
                viewStartTimeField1.setText(aStartTime);
                viewEndTimeField1.setText(aEndTime);
            }
            else if (aJList == cancelBookingJList)
            {
                viewCustomerField.setText(aCustomer);
                viewRoomField.setText(aRoom);
                viewDateField.setText(aDate);
                viewStartTimeField.setText(aStartTime);
                viewEndTimeField.setText(aEndTime);
            }
        }
    }
}
